name: Deploy
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Install step
        run: " npm install "

      - name: Build step
        run: "dotenv -e .env && npx prisma generate && npx prisma migrate deploy --schema=src/prisma/schema.prisma && npm run start:prod"

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "macacao-backend"
          entrypoint: "https://github.com/chimpsltda/dieta-treino/tree/main/src/main.ts"
          root: "https://github.com/chimpsltda/dieta-treino/tree/main/"
